name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        working-directory: python-fast-app  # Change directory to where requirements.txt is located
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: python-fast-app  # Change directory to where your tests are located
        run: |
          pytest  # Adjust if you're using a different test runner

      - name: Build and Deploy
        run: |
          # Your build and deploy commands here

